version: '3'
services:
  wanted-pre-onboarding-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 8080:8080
    container_name:
      subjectApp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/subject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - subject_network
    stdin_open: true
    tty: true

  database:
    image: mysql
    container_name: subject_backend_db
    environment:
      - MYSQL_DATABASE=subject
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - subject_network
    stdin_open: true
    tty: true

networks:
  subject_network:

